apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: karsajob-ns
  name: karsajobs-ui 
  labels:
    app: karsajobs-ui
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: karsajobs-ui
  template:
    metadata:
      namespace: karsajob-ns
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: ghcr.io/vikraam27/karsajobs-ui:latest
          ports:
            - containerPort: 8000
          # Set resource pod
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"