apiVersion: v1
kind: Service
metadata:
  namespace: karsajob-ns
  name: mongo-svc
  labels:
    app: mongo
spec:
  ports:
  # Default port mongodb
  - port: 27017
  # Use tcp/ip as protocol
    protocol: TCP
  selector:
    app: mongo
    tier: backend
  # Set cluster ip none 
  clusterIP: None